[package]
name = "sigma-authentication"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
rocket = { version = "0.5.1", features = ["json"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-native-tls", "postgres"] }

[dev-dependencies]
testcontainers = "0.23.3"
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
