name: CI (build and test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Run build
      run: cargo build --verbose

    - name: Run tests with nextest
      run: cargo nextest run --all
