name: Build and Deploy Docker Image to K3S

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: andrew4coding/sigma-auth

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: SSH and deploy to K3S
        run: |
          echo "${{ secrets.SSH_PASSWORD }}" | sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e

            IMAGE=${{ env.IMAGE_NAME }}:${{ github.sha }}
            DEPLOYMENT_NAME=sigma-auth
            CONTAINER_NAME=sigma-auth

            echo "Setting new image: \$IMAGE"
            kubectl set image deployment/\$DEPLOYMENT_NAME \$CONTAINER_NAME=\$IMAGE --namespace=default

            echo "Waiting for rollout to finish..."
            if ! kubectl rollout status deployment/\$DEPLOYMENT_NAME --timeout=60s --namespace=default; then
              echo "❌ Rollout failed. Performing rollback..."
              kubectl rollout undo deployment/\$DEPLOYMENT_NAME --namespace=default
              exit 1
            fi

            echo "✅ Deployment succeeded"
          EOF
